import { Book } from '@/types';

// 리틀크랙 캐릭터 데이터 - 크래커스 스튜디오 제공
export const books: Book[] = [
  {
    id: 1,
    title: "토끼 크랙이",
    author: "Little Crack",
    coverImage: "https://cdn.imweb.me/thumbnail/20250527/38f44f6d8209f.png",
    audioFile: "/audio/rabbit.mp3",
    description: "귀여운 토끼 캐릭터입니다",
    genre: "Character",
    publishedYear: 2024,
  },
  {
    id: 2,
    title: "곰 크랙이",
    author: "Little Crack",
    coverImage: "https://cdn.imweb.me/thumbnail/20250527/9318aa38c687d.png",
    audioFile: "/audio/bear.mp3",
    description: "따뜻한 곰 캐릭터입니다",
    genre: "Character",
    publishedYear: 2024,
  },
  {
    id: 3,
    title: "고양이 크랙이",
    author: "Little Crack",
    coverImage: "https://cdn.imweb.me/thumbnail/20250527/e927347749a74.png",
    audioFile: "/audio/cat.mp3",
    description: "사랑스러운 고양이 캐릭터입니다",
    genre: "Character",
    publishedYear: 2024,
  },
  {
    id: 4,
    title: "여우 크랙이",
    author: "Little Crack",
    coverImage: "https://cdn.imweb.me/thumbnail/20250527/a5ed1506d849f.png",
    audioFile: "/audio/fox.mp3",
    description: "똑똑한 여우 캐릭터입니다",
    genre: "Character",
    publishedYear: 2024,
  },
  {
    id: 5,
    title: "사슴 크랙이",
    author: "Little Crack",
    coverImage: "https://cdn.imweb.me/thumbnail/20250527/cdb3d1e8d380a.png",
    audioFile: "/audio/deer.mp3",
    description: "우아한 사슴 캐릭터입니다",
    genre: "Character",
    publishedYear: 2024,
  },
  {
    id: 6,
    title: "펭귄 크랙이",
    author: "Little Crack",
    coverImage: "https://cdn.imweb.me/thumbnail/20250527/c5ea4ef8a3a7e.png",
    audioFile: "/audio/penguin.mp3",
    description: "깜찍한 펭귄 캐릭터입니다",
    genre: "Character",
    publishedYear: 2024,
  },
];
